all:
  hosts:
    app_server:
      ansible_host: 18.119.203.160
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/poc_infra
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
